[package]
name = "smart_relay"
version = "0.1.0"
edition = "2024"
authors = ["Dmitry Akimov <akimov@machunit.com>"]

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
range-parser = "0.1.2"