[package]
name = "smart_relay"
version = "0.1.0"
edition = "2021"
authors = ["Dmitry Akimov <akimov@machunit.com>"]

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
range-parser = "0.1.2"
serialport = "4.7.2"
ascii_converter = "0.3.0"
hex="0.4.3"
chrono = "0.4.26"